---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r}
  # Repo
  #       The Repo was forked  on 2015-Apr-15 at 06:40 a.m. pt
  #       The Repo was clonned on 2015-Apr-15 at 06:49 a.m. pt

  # Data 
  #       AMD      - Activity Monitoring Data
  #       Source   - https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip
  #                  Size - 52K
  #                  It is zipped
  #                  Records - 17,568
  #       Variables-
  #                  Steps    - No of.. or NA (Missing Value)
  #                  Date     - (YYYY-MM-DD)
  #                  Interval - Identifier for the 5-minute interval in which measurement was taken
 


  # Clean up workspace
        rm(list=ls()); 
        
  # set working directory 
        setwd('C:/Users/hgrisales/Documents/Coursera/AMD'); 

  # Load the data 
  # The file was downloaded on 2015-Apr-15 at 06:33 a.m. pt
        raw_data <- read.csv("activity.csv" , header=TRUE)

  # Explore the data
        head(raw_data)
        summary(raw_data)

  # Split the data
        Total_Steps_By_Day_without_NA <-aggregate(steps~date, data=raw_data,sum, na.rm=TRUE)

        summary(Total_Steps_By_Day_without_NA)
        
```


## What is mean total number of steps taken per day?

```{r}

  # Mean Total steps by Day
   mean(Total_Steps_By_Day_without_NA$steps)

# Median Total steps by Day
   median(Total_Steps_By_Day_without_NA$steps, na.rm = TRUE)

# Histogram - distribution of total number of steps per day

   barplot(Total_Steps_By_Day_without_NA$steps, names.arg =Total_Steps_By_Day_without_NA$date, main="Number of Steps per Day",xlab="Date", ylab="Steps", col=c("green"))

```

## What is the average daily activity pattern?

```{r}
    # Create a date-time column that combines the date and interval columns.

        DateTime <- formatC(raw_data$interval/100, 2, format = "f")
        raw_data$date.DateTime <- as.POSIXct(paste(raw_data$date, DateTime),format = "%Y-%m-%d %H.%M", tz = "GMT") 

        raw_data$DateTime <- format(raw_data$date.DateTime, format = "%H:%M:%S")
        raw_data$DateTime <- as.POSIXct(raw_data$DateTime, format = "%H:%M:%S")

        mean.steps <- tapply(raw_data$steps, raw_data$DateTime, mean, na.rm = TRUE)
        daily.pattern <- data.frame(DateTime = as.POSIXct(names(mean.steps)), mean.steps = mean.steps)

       
       plot(daily.pattern$DateTime, daily.pattern$mean.steps, type = "l", xlab = "Time of the day - 5-min Interval", ylab = "Average Num of Steps", main = "Average Daily Activity Pattern")


```

## Imputing missing values

```{r}
   
    na_records <- nrow(raw_data[!complete.cases(raw_data),])
    print(sprintf("Records wit NA data: %i ", na_records))

   #  Methodology:
   #  Replace NA step values- use mean steps for a five-minute interval for the entire dataset

        Average_Steps_By_Interval <-aggregate(steps~ interval , data=raw_data,mean, na.rm=TRUE)

        raw_data <- merge(raw_data,Average_Steps_By_Interval, by = "interval", suffixes = c("",".y"))
        nas <- is.na(raw_data$steps)
        raw_data$steps[nas] <- raw_data$steps.y[nas]
        raw_data_new <- raw_data[, c(1:3)]

        steps_per_day<-aggregate(steps ~ date, raw_data_new, sum)
        barplot(steps_per_day$steps, names.arg=steps_per_day$date, xlab="date", ylab="steps", main="Number of steps per day", col="red")



```

## Are there differences in activity patterns between weekdays and weekends?


```{r}
        library(lattice)
        raw_data_new$date<-as.Date(raw_data_new$date,format = '%Y-%m-%d')
        raw_data_new$day <- ifelse(weekdays(raw_data_new$date) %in% c("Saturday", "Sunday"),'weekend','weekday')
        head(raw_data_new)

        steps_by_interval_and_Daytype<-aggregate(steps~ interval+day,raw_data_new,FUN="mean")
        head(steps_by_interval_and_Daytype)

        library(lattice)
        xyplot(steps ~ interval | day, steps_by_interval_and_Daytype, layout = c(2, 1), type = "l", col="blue", xlab="interval", ylab="interval")



```
